---

networks:
  ocean: 
    external: true
  lagoon:
    external: true

volumes:
  qbittorrent_ts:
  radarr_ts:
  sonarr_ts:
  ombi_ts:
  prowlarr_ts:

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    privileged: true
    env_file: ../tskey.env
    environment:
      - PUID=984
      - PGID=100
      - TZ=America/Montreal
      - UMASK=022
      - WEBUI_PORT=80
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main|ghcr.io/vuetorrent/vuetorrent-lsio-mod:latest
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_HOSTNAME=qb
    volumes:
      - qbittorrent_ts:/var/lib/tailscale
      - /srv/qbittorrent:/config
      - ./qb/notify.sh:/config/notify.sh
      - /d/ruby:/ruby
      - /d/ruby/torrents:/torrents
      - /d/ruby/downloads:/downloads
      - /d/emerald:/emerald
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      lagoon:
        aliases: ["qb"]
      ocean:
        ipv4_address: 192.168.2.210
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    privileged: true
    env_file: ../tskey.env
    environment:
      - PUID=984
      - PGID=100
      - TZ=America/Montreal
      - UMASK=022 #optional
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main|linuxserver/mods:radarr-striptracks
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_HOSTNAME=radarr
      - STRIPTRACKS_ARGS=--audio :eng:fre --subs :eng:fre
    volumes:
      - radarr_ts:/var/lib/tailscale
      - /srv/radarr:/config
      - /l/backup/sklad/radarr:/config/Backups
      - ./radarr:/scripts
      - /d/emerald:/emerald
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      lagoon:
        aliases: ["rdr"]
      ocean:
        ipv4_address: 192.168.2.211
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    privileged: true
    env_file: ../tskey.env
    environment:
      - PUID=984
      - PGID=100
      - TZ=America/Montreal
      - UMASK=022 #optional
      - DOCKER_MODS=ghcr.io/tailscale-dev/docker-mod:main|linuxserver/mods:radarr-striptracks
      - TAILSCALE_STATE_DIR=/var/lib/tailscale
      - TAILSCALE_SERVE_MODE=https
      - TAILSCALE_SERVE_PORT=80
      - TAILSCALE_HOSTNAME=sonarr
      - STRIPTRACKS_ARGS=--audio :eng:fre --subs :eng:fre
      # - TAILSCALE_AUTHKEY=${TSKEY}
    volumes:
      - sonarr_ts:/var/lib/tailscale
      - /srv/sonarr:/config
      - /l/backup/sklad/sonarr:/config/Backups
      - /d/emerald:/emerald
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      lagoon:
        aliases: ["snr"]
      ocean:
        ipv4_address: 192.168.2.212
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Montreal
      - AUTO_UPDATE=false
    volumes:
      - /srv/jackett:/config
    networks:
      lagoon:
        aliases: ["jkt"]
      ocean:
        ipv4_address: 192.168.2.213
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland

  byparr: # Port 8191
    image: ghcr.io/thephaseless/byparr:latest
    container_name: byparr
    environment:
      - TZ=America/Montreal
    volumes:
      - /dev/null:/app/screenshots # For screenshots when exception occurs
    networks:
      - lagoon
    restart: unless-stopped
    labels:
      - falarie.groupby=pirateisland