networks:
  lagoon:
    external: true

volumes:
  radicale_ts:

services:
  ts_radicale:
    image: tailscale/tailscale
    container_name: ts_radicale
    cap_add:
      - net_admin
      - sys_module
    env_file: ../tskey.env
    environment:
      - TZ=America/Montreal
      - TS_HOSTNAME=radicale
      - TS_EXTRA_ARGS=--accept-dns=false
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_SERVE_CONFIG=/config/serve.json
    volumes:
      - radicale_ts:/var/lib/tailscale
      - ./ts_radicale:/config
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - lagoon
    restart: unless-stopped

  radicale: # https://github.com/tomsquest/docker-radicale
    image: tomsquest/docker-radicale
    container_name: radicale
    depends_on: [ts_radicale]
    healthcheck:
      test: curl -f http://127.0.0.1:5232 || exit 1
      interval: 5m
      retries: 3
    network_mode: service:ts_radicale
    volumes:
      - /data/containers/radicale/config:/config
      - /data/containers/radicale/data:/data/collections
    restart: unless-stopped
