---

networks:
  johnny:
    external: true

  lagoon:
    external: true

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    env_file:
      - ~/secrets/mariadb.env
    environment:
      - PUID=990
      - PGID=990
      - TZ=America/Montreal
      # - MYSQL_ROOT_PASSWORD=
      # - MYSQL_DATABASE=USER_DB_NAME #optional
      # - MYSQL_USER=MYSQL_USER #optional
      # - MYSQL_PASSWORD=DATABASE_PASSWORD #optional
      # - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /data/containers/mariadb:/config
      - /l/backup/raktar/mariadb:/backup
    networks:
      lagoon:
        aliases:
          - "db"
      johnny:
        ipv4_address: 192.168.2.193
    ports:
      - 3306:3306
    restart: unless-stopped
    labels:
      - falarie.groupby=database

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin
    container_name: phpmyadmin
    env_file:
      - ~/secrets/phpmyadmin.env
    environment:
      - TZ=America/Montreal
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      # - PMA_ARBITRARY=1
      # - PMA_USER=
      # - PMA_PASSWORD=
    volumes:
      - /data/containers/phpmyadmin/config:/config
    network_mode: service:mariadb
    restart: unless-stopped
    labels:
      - falarie.groupby=database
